spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

jwt-token:
  expiration-time: 86400000 # 1 day
  secret-key: laonzenamoon
